install:
  - curl -sSf https://static.rust-lang.org/dist/rust-1.11.0-x86_64-pc-windows-msvc.exe -o rust.exe
  - rust.exe /VERYSILENT /NORESTART /DIR="C:\Rust"
  - set PATH=%PATH%;C:\Rust\bin

  - curl -sSf http://llvm.org/releases/3.8.0/LLVM-3.8.0-win64.exe -o LLVM.exe
  - 7z x LLVM.exe -oC:\LLVM
  - set PATH=%PATH%;C:\LLVM\bin
  - set LIBCLANG_PATH=C:\LLVM\bin

build_script:
  - cargo build --verbose --release --features clang_3_8

test_script:
  - set RUST_BACKTRACE=1
  - set RUST_TEST_THREADS=1
  - cargo test --verbose -- --nocapture
