install:
  - curl -sSf https://static.rust-lang.org/dist/rust-1.11.0-x86_64-pc-windows-msvc.exe -o rust.exe
  - rust.exe /VERYSILENT /NORESTART /DIR="C:\Rust"
  - set PATH=%PATH%;C:\Rust\bin

  - curl -sSf http://llvm.org/releases/3.8.0/LLVM-3.8.0-win64.exe -o LLVM.exe
  - 7z x LLVM.exe -oC:\LLVM
  - set PATH=%PATH%;C:\LLVM\bin
  - set LIBCLANG_PATH=C:\LLVM\bin

build_script:
  - cargo build --verbose --release --features clang_3_8
  - md deploy
  - move target\release\cpp_codegen_rs.exe deploy\cpp_codegen_windows.exe
  - copy C:\LLVM\bin\libclang.dll deploy\libclang.dll
  - 7z a cpp_codegen_windows.zip deploy\*.*

test_script:
  - set RUST_BACKTRACE=1
  - set RUST_TEST_THREADS=1
  - cargo test --verbose -- --nocapture

artifacts:
  - path: cpp_codegen_windows.zip
    name: Releases

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: aFuuIGpdj5nf4v6gDDv1bfL3Jhkk4ktsY3SC0WICL+2w2RDOH/xK1HVq2Dl3Ehnp
  artifact: cpp_codegen_windows.zip
  on:
    appveyor_repo_tag: true
